name: Generate Markdown TOC

on:
  push:
    branches:
      - '**'

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate Table of Contents
      run: python app.py

    - name: Commit changes
      run: |
        git config user.name "SinghTaran301"
        git config user.email "taran4486@gmail.com"
        git add .
        git commit -m "Update TOC [skip ci]"
        git push
